exports.EDGE = {
  rising: "rising",
  falling: "falling",
  both: "both",
};

exports.DIRECTION = {
  in: "in",
  high: "high",
  low: "low",
};

exports.PHYSICAL_TO_GPIO = {
  3: 2,
  5: 3,
  7: 4,
  8: 14,
  10: 15,
  11: 17,
  12: 18,
  13: 27,
  15: 22,
  16: 23,
  18: 24,
  19: 10,
  21: 9,
  22: 25,
  23: 11,
  24: 8,
  26: 7,
  29: 5,
  31: 6,
  32: 12,
  33: 13,
  35: 19,
  36: 16,
  37: 26,
  38: 20,
  40: 21,
};

exports.LINE_FEED = "\n";

exports.DEFAULT_WINDOW = 60;

exports.DEFAULT_M_C = 1;

exports.PAUSE_DELAY = 2500;

exports.LOADING_TIMER = 5000;

exports.LOADING_PAUSE = 200;

exports.TEST_IN_PROGRESS = "TEST_IN_PROGRESS";

exports.CALIBRATION_ST_CYCLES = 3;

const CALIBRATION_MIN_POINTS = 3;

exports.CALIBRATION_MIN_POINTS = CALIBRATION_MIN_POINTS;

exports.CALIBRATION_MAX_MOVES = 1 + CALIBRATION_MIN_POINTS * 4 + 2;

exports.EVENTS = {
  WATCH_CADENCE: "WATCH_CADENCE",
  WATCH_PROGRAMS: "WATCH_PROGRAMS",
  GET_PROGRAMS: "GET_PROGRAMS",
  WATCH_SETTINGS: "WATCH_SETTINGS",
  GET_SETTINGS: "GET_SETTINGS",
  WATCH_BOOT: "WATCH_BOOT",
  GET_BOOT: "GET_BOOT",
  CHECK_PROGRAM_TITLE: "CHECK_PROGRAM_TITLE",
  SET_FULLSCREEN: "SET_FULLSCREEN",
  GET_POTENTIOMETER: "GET_POTENTIOMETER",
  DANGER_MOVE_FORWARD: "DANGER_MOVE_FORWARD",
  DANGER_MOVE_BACK: "DANGER_MOVE_BACK",
  MOTOR_CALIBRATION: "MOTOR_CALIBRATION",
  SET_MOTOR_LEVEL: "SET_MOTOR_LEVEL",
  STOP_MOTOR: "STOP_MOTOR",
  PREVENT_DISPLAY_SLEEP: "PREVENT_DISPLAY_SLEEP",
  EDIT_PROGRAM: "EDIT_PROGRAM",
  EDIT_SETTINGS: "EDIT_SETTINGS",
  EDIT_BOOT_CONFIG: "EDIT_BOOT_CONFIG",
  SAVE_NEW_PROGRAM: "SAVE_NEW_PROGRAM",
  DELETE_PROGRAM: "DELETE_PROGRAM",
  APP_QUIT: "APP_QUIT",
};

exports.LANGS_CODES = { en: "en", ru: "ru" };

exports.DOT_JSON = ".json";

exports.ABSOLUTE_DIR_CONST = {
  BOOT: "/boot",
};

exports.DIR_CONST = {
  SETTINGS: "settings",
  EXERCISES: "exercises",
  PROGRAMS: "programs",
};

exports.FILE_CONST = {
  INTERFACE: "interface.json",
  PERIPHERAL: "peripheral.json",
  CONFIG: "config.txt",
};

exports.BOOT_CONFIG_OPT = { SPI: "SPI" };

exports.MOTOR_FIELDS = {
  MIN_POS: "minPosition",
  MAX_POS: "maxPosition",
  SLEEP_RATIO: "sleepRatio",
  SWAP_MOTOR_WIRES: "swappedMotorWires",
  SWAP_POTEN_WIRES: "swappedPotentiometerWires",
};

exports.MOVE_DIRECTION = { forward: "forward", back: "back" };

exports.ERRORS = {
  GPIO_EPERM: "GPIO_EPERM",
  POTEN_ERROR: "POTEN_ERROR",
  INVALID_RESIST_LEVEL: "INVALID_RESIST_LEVEL",
  LOADING_TIMER_EXPIRED: "LOADING_TIMER_EXPIRED",
  CALIBRATION_NO_DATA: "CALIBRATION_NO_DATA",
  CALIBRATION_INVALID_EDGES: "CALIBRATION_INVALID_EDGES",
  CALIBRATION_WRONG_DIRECTION: "CALIBRATION_WRONG_DIRECTION",
  CALIBRATION_HINDRANCE: "CALIBRATION_HINDRANCE",
  CALIBRATION_TOO_LONG: "CALIBRATION_TOO_LONG",
  CALIBRATION_UNKNOWN: "CALIBRATION_UNKNOWN",
  PROMISE_CANCELLED: "PROMISE_CANCELLED",
  BOOT_CONFIG_NOT_EXIST: "BOOT_CONFIG_NOT_EXIST",
  BOOT_CONFIG_WRONG_ARGS: "BOOT_CONFIG_WRONG_ARGS",
};
