export const NAMES = { ipcApi: "ipcApi", environment: "environment" };

export const EVENTS = {
  WATCH_CADENCE: "WATCH_CADENCE",
  WATCH_PROGRAMS: "WATCH_PROGRAMS",
  GET_PROGRAMS: "GET_PROGRAMS",
  WATCH_SETTINGS: "WATCH_SETTINGS",
  GET_SETTINGS: "GET_SETTINGS",
  WATCH_BOOT: "WATCH_BOOT",
  GET_BOOT: "GET_BOOT",
  CHECK_PROGRAM_TITLE: "CHECK_PROGRAM_TITLE",
  SET_FULLSCREEN: "SET_FULLSCREEN",
  GET_POTENTIOMETER: "GET_POTENTIOMETER",
  DANGER_MOVE_FORWARD: "DANGER_MOVE_FORWARD",
  DANGER_MOVE_BACK: "DANGER_MOVE_BACK",
  MOTOR_CALIBRATION: "MOTOR_CALIBRATION",
  SET_MOTOR_LEVEL: "SET_MOTOR_LEVEL",
  STOP_MOTOR: "STOP_MOTOR",
  PREVENT_DISPLAY_SLEEP: "PREVENT_DISPLAY_SLEEP",
  EDIT_PROGRAM: "EDIT_PROGRAM",
  EDIT_SETTINGS: "EDIT_SETTINGS",
  EDIT_BOOT_CONFIG: "EDIT_BOOT_CONFIG",
  SAVE_NEW_PROGRAM: "SAVE_NEW_PROGRAM",
  DELETE_PROGRAM: "DELETE_PROGRAM",
  APP_QUIT: "APP_QUIT",
};

export const RUNNINIG_STATUS = { RUN: "RUN", PAUSE: "PAUSE" };

export const PAUSE_DELAY = 2500;

export const FILE_CONST = {
  INTERFACE: "interface.json",
  PERIPHERAL: "peripheral.json",
  CONFIG: "config.txt",
};

export const BOOT_CONFIG_OPT = { SPI: "SPI" };
