export const NAMES = {
  ipcApi: "ipcApi",
  environment: "environment",
};

export const EVENTS = {
  WATCH_CADENCE: "WATCH_CADENCE",
  WATCH_PROGRAMS: "WATCH_PROGRAMS",
  GET_PROGRAMS: "GET_PROGRAMS",
  CHECK_PROGRAM_TITLE: "CHECK_PROGRAM_TITLE",
  SET_FULLSCREEN: "SET_FULLSCREEN",
  SET_MOTOR_LEVEL: "SET_MOTOR_LEVEL",
  STOP_MOTOR: "STOP_MOTOR",
  PREVENT_DISPLAY_SLEEP: "PREVENT_DISPLAY_SLEEP",
  EDIT_PROGRAM: "EDIT_PROGRAM",
  SAVE_NEW_PROGRAM: "SAVE_NEW_PROGRAM",
  DELETE_PROGRAM: "DELETE_PROGRAM",
  APP_QUIT: "APP_QUIT",
};

export const RUNNINIG_STATUS = {
  RUN: "RUN",
  PAUSE: "PAUSE",
};

export const PAUSE_DELAY = 2500;
